fix profiler table name generation
monosidev/monosi pull request #25
Opened 2022-01-19 00:34 UTC by iporollo

## Description

Fixing #21 to generate correct table name strings

## Notes
This does affect the file names as well. That said, I believe this is better because it profiles more accurately now (previously if table names were the same in different schema, they would be overwritten)

![image](https://user-images.githubusercontent.com/14094284/150041012-11267c7d-2199-4ba5-835e-32798df7cf77.png)

2022-01-19 00:38 UTC, unkrich commented
This doesn't fix the core issue. The profiler is not the actual problem. The problem is in parsing the name and resolving it to a fully qualified table name

2022-01-19 00:39 UTC, unkrich requested changes
See previous comment

2022-01-19 02:33 UTC, unkrich commented on monosi/profiler.py
> +            table_name_elements = [row['DATABASE'], row['SCHEMA'], row['NAME']]
Not sure we should assume database and schema are for sure returned here
```
table_name_elements = list(filter(lambda x: x is not None, [row['DATABASE'], row['SCHEMA'], row['NAME']]))
```

2022-01-20 02:33 UTC, iporollo commented
Closing for now, will re-open with updated changes + base branch

2022-01-20 02:33 UTC, closed without merging